// packages/solid/src/index.ts
import { defineLayoutRenderer } from 'saus/core'
import { JSX } from 'solid-js/types/jsx'
import { generateHydrationScript, renderToStringAsync } from 'solid-js/web'

export const defineLayout = defineLayoutRenderer<() => JSX.Element>({
  hydrator: '@saus/solid/hydrator',
  toString: renderToStringAsync,
  head: generateHydrationScript,
})

// packages/react/src/index.ts
import * as ReactDOM from 'react-dom/server'
import { addConfigHook, defineLayoutRenderer } from 'saus/core'
import './stack'

addConfigHook('./vite.config')

export const defineLayout = defineLayoutRenderer({
  hydrator: '@saus/react/hydrator/index.tsx',
  toString: (result: JSX.Element | null) =>
    result ? ReactDOM.renderToString(result) : '',
})

export * from './types'

declare module 'saus/core' {
  export interface UserConfig {
    babel?: import('@vitejs/plugin-react').BabelOptions
    react?: Omit<import('@vitejs/plugin-react').Options, 'babel'>
  }
}
